ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.17.0.0/16
    clusterPoolIPv4MaskSize: 24

operator:
  replicas: 3

externalIPs:
  enabled: true

dnsProxy:
  dnsRejectResponseCode: nameError

cni:
  exclusive: true

bpf:
  policyMapMax: 32768

global:
  encryption:
    enabled: true
    nodeEncryption: true

policyEnforcementMode: default

l2announcements:
  enabled: true

k8sClientRateLimit:
  qps: 100
  burst: 200

kubeProxyReplacement: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

image:
  repository: "quay.io/cilium/cilium"
  tag: "v1.16.1"
  digest: "sha256:0b4a3ab41a4760d86b7fc945b8783747ba27f29dac30dd434d94f2c9e3679f39"

priorityClassName: system-node-critical

annotateK8sNode: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

hubble:
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http

  ui:
    enabled: true
    replicas: 1
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: cloudflare
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-signin: https://authentik.mcswain.dev/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/configuration-snippet: expires -1;
      hosts:
        - hubble.mcswain.dev
      tls:
        - secretName: hubble.mcswain.dev-tls
          hosts:
            - hubble.mcswain.dev

  relay:
    enabled: true

LBIPAM:
  requireLBClass: true