machine:
  type: worker
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn-ssd
        type: bind
        source: /var/lib/longhorn-ssd
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/longhorn-nvme-1
        type: bind
        source: /var/lib/longhorn-nvme-1
        options:
          - bind
          - rshared
          - rw
      - destination: /var/lib/longhorn-nvme-2
        type: bind
        source: /var/lib/longhorn-nvme-2
        options:
          - bind
          - rshared
          - rw
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: overlay
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: br_netfilter
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: mlx4_en
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: uvcvideo
